package com.fredtm.desktop.controller.utils;

public enum FredCharts {

	TIME_BY_CLASSIFICATION, 
	TIME_BY_SIMPLE_CLASSIFICATION, 
	TIME_ANALYSYS,
	CICLE_BARS_CLASSIFICATION,
	TIME_ACTIVITY_DISTRIBUTION,
	MULTIPLE_TIME_ANALYSYS;

}
