package com.fredtm.desktop.controller.utils;

public enum FredCharts {

	BARS_CLASSIFICATION, 
	CICLE_BARS_CLASSIFICATION,
	ATIVIDADES_LINHA_TEMPORAL, 
	DISTRIBUICAO_TEMPO_PARETO, 
	TIME_ACTIVITY_DISTRIBUTION;

}
