package com.fredtm.desktop.controller.utils;

public enum GraphicsOptions {

	CLASSIFICACAO_POR_BARRAS, 
	CLASSIFICACAO_CICLOS_POR_BARRAS,
	ATIVIDADES_LINHA_TEMPORAL, 
	DISTRIBUICAO_TEMPO_PARETO, 
	DISTRIBUICAO_TEMPO_ATIVIDADE_PIZZA;

}
